### ISSUE TITLE
Discourse auto-posting is repeating for old blog posts

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-blog#121]
Looks like despite our best efforts, the `system` blog bot posted for every blog post in the switchover. Good news is the bot was muted 😊 

Opening this issue to see how to proceed after ...
- Initial burst of forum posts stops
- We post a few _new_ blog posts and watch the bot react

Most likely we can just switch the bot back on at that point, but TBD.

**Comment by jessicaschilling** [comment]
Looks like the bot backlog is cleared - now just waiting to see how it behaves the next time we publish a post. The next weekly newsletter should go out in the next day or two; I'll keep an eye on this.

**Comment by jessicaschilling** [comment]
@zebateira -- I'm afraid I need to ask for your help on this one, as the auto-posting isn't stopping. Have sent you an invite to the Discourse board; please let me know when you're in and I'll get you set up as an admin for the hopes of digging deeper. 🙏

**Comment by zebateira** [comment]
@jessicaschilling I'm in 👍

**Comment by zebateira** [comment]
@lidel said:

> In the past we used http://ipfs.io/blog but then moved to http://blog.ipfs.io and old website had code that adjusted the canonical link for comments based on post publication date. New website did not port this logic, and that is why visiting old posts created new topics.
> Note that this not just us testing, but also google and other bot crawlers.
> Every page will be visited eventually, all missing topics will get created, and then things will calm down.
> Backporting old logic would would stop topic creation, but at this point i dont think its worth it – mess already hapepned, and there is a finite number of blogposts, so its better to let them be created and dont add any complexity to the new blog website.

Said logic is here: https://github.com/ipfs-inactive/blog/blob/616abde2224569f2b0a010117da7ccada44fb109/layouts/post/single.html#L25

@jessicaschilling ok to let it go through all the posts (unlisted, no public spamming) so it will stop doing it by itself?

**Comment by zebateira** [comment]
the other alternative would be to port the logic and then delete the new created posts.

**Comment by jessicaschilling** [comment]
This makes more sense, thank you for looking in to it. 😊 
I could also just make a pot of coffee and open every blog post to force the issue (though I believe discourse rate limits pretty hard - might need to break this up into a bunch of cups of coffee rather than a whole pot at once).

**Comment by jessicaschilling** [comment]
Looks like this has died down — I turned off the auto-mute feature in Discourse for blog posts.

cc @hsanjuan for visibility, as I believe he was the one who initially auto-muted that category.
