### ISSUE TITLE
normalize tags and author keys

### ISSUE THREAD

**Issue by cwaring** [ipfs/ipfs-blog#154]
### Problem

Currently tags and authors are case sensitive and expressed in plain text resulting in ugly/fragile preview urls:

`?author=Kyle%20Drake&tags=go-ipfs,bootstrap%20nodes,breaking%20change`

### Suggestion:

Use this included `slug` module to enforce urls into lower kebab-case keys and match the objects in a case insensitive way:

`?author=kyle-drake&tags=go-ipfs,bootstrap-nodes,breaking-change`

It would be best to do this sooner rather than later so that we don't end up with too many inbound links using the current structure.

**Comment by zebateira** [comment]
Sounds good 👍 
Should we support the old format to not break old links?

**Comment by cwaring** [comment]
I think we're early enough for that not to be an issue yet, plus and unrecognised links will just fall back to the blog index.

**Comment by jessicaschilling** [comment]
Suggest we **do** fall back for category types with spaces in them - eg news releases - as there are definitely links directly to those in circulation.

**Comment by cwaring** [comment]
If it doesn't add too much complexity then yes that would be great also. It will only affect `%20` items, so weighing it up implementation cost against that.

**Comment by jessicaschilling** [comment]
@jdiogopeixoto Just checking in on this one? Thank you!

**Comment by jdiogopeixoto** [comment]
@jessicaschilling I'm finishing the work on this one. Tomorrow I should be done.
