### ISSUE TITLE
Forestry: date picker is not working properly (date can't be selected)

### ISSUE THREAD

**Issue by zebateira** [ipfs/ipfs-blog#194]
I contacted forestry support and will update this issue with updates from them.

Recording of issue:

https://user-images.githubusercontent.com/2353186/118000573-d736c580-b33d-11eb-9ad4-1ae85eb10038.mp4

**Comment by zebateira** [comment]
Just heard back from the forestry team. They are aware of this bug.
They have sent us a workaround for this:

1. In the app setttings, change the timezone to your own timezone:

![Screen Shot 2021-05-14 at 1 07 45 PM](https://user-images.githubusercontent.com/2353186/118268558-6c0fff00-b4b5-11eb-9981-51c1fc9b64f2.png)

2. Go back to the content and change the date, it should now work.

**Comment by jessicaschilling** [comment]
Thanks @zebateira! Tagging @emilymvaughan @achingbrain @jennwrites @lidel @autonome here, as they're the main folks likely to be affected by this. Will also send on Slack for good measure. Closing this issue 😊
