### ISSUE TITLE
Automatic sync between staging and main

### ISSUE THREAD

**Issue by zebateira** [ipfs/ipfs-blog#200]
Since stating falls behind on main when new dev changes have been made, would be beneficial to have an automatic trigger to update the staging branch.
We can do this using a github action to automatically merge main into staging.

**Comment by jessicaschilling** [comment]
Much better than my manually doing it. Would you have time to build this at some point?

**Comment by zebateira** [comment]
@jessicaschilling yes, this week I can make it happen 😊
