### ISSUE TITLE
Unable to add additional comments to blog posts

### ISSUE THREAD

**Issue by cwaring** [ipfs/ipfs-blog#212]
1. Navigate to a blog post: https://blog.ipfs.io/2021-05-05-audius-uses-ipfs-web3-video/
2. Scroll down the comments section
3. If existing comments exist there is no link to navigate to the forum

Screenshot:
![2021-05-24 at 12 22 20](https://user-images.githubusercontent.com/106938/119340762-dc273d80-bc8a-11eb-874e-d33f64857ce0.png)

**Comment by jessicaschilling** [comment]
This is unfortunately a Discourse-related issue that appears intermittently, and not something that can be mitigated on this end.

**Comment by cwaring** [comment]
Do we know the discourse url at the time of posting? If so we could link the comments heading to it as a work around.

**Comment by jessicaschilling** [comment]
Not at time of posting. Could do after the fact. But it does seem to appear intermittently and not permanently.
