### ISSUE TITLE
General code audit

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-blog#34]
This issue is for the need for an overall code audit, focusing in particular on:
- Modules etc that could be removed as a result of being ported over from PL blog but not needed here
- Potential barriers to deployment over IPFS

Please separate the results out into their own issues so they're easier to work - thanks!

**Comment by zebateira** [comment]
@cwaring does this feel like it's complete? Or do you want another iteration after launch?

**Comment by cwaring** [comment]
It looks like we've covered all the burning issues now but we should do another round to actually check over optimisations and configuration, I haven't had time to go much deeper in this sprint.

Calling this complete for now so we can move onto the pre-flight transition!
