### ISSUE TITLE
[Blog Post] libp2p and The Merge

### ISSUE THREAD

**Issue by BigLep** [ipfs/ipfs-blog#489]
# Done criteria

Post making it clear that libp2p is securing Ethereum now, recapping how we got there and some of the metrics on networks libp2p is securing.

**Comment by p-shahi** [comment]
Can't transfer issues across orgs, tracking here instead: https://github.com/libp2p/blog/issues/8

**Comment by p-shahi** [comment]
@BigLep please close this issue, I'm not able to.
