### ISSUE TITLE
Change references to "weekly newsletter" to just "newsletter" (as it is no longer weekly)

### ISSUE THREAD

**Issue by damedoteth** [ipfs/ipfs-blog#540]
The IPFS Newsletter is no longer weekly, and is likely going to be monthly instead. I am the new lead for it. I would like for all references of "weekly" to be removed so that we are just referring to it as our "newsletter" or the "IPFS Newsletter". 

Above the blog filters:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/110121581/225725019-262d4688-e84b-4bad-9253-513e4bc833e3.png">

In the tags of the posts:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/110121581/225726066-23c6a116-128a-4082-b236-191e2478811a.png">

In the footer: 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/110121581/225726238-366513e1-aad2-48d5-8878-d359b60c718f.png">

In the URLs:
<img width="272" alt="image" src="https://user-images.githubusercontent.com/110121581/225726385-ab3a7468-600b-4c55-9117-094060be3093.png">

Ideally the URLs would change to this format: https://blog.ipfs.tech/news-191/ 

With the old links redirecting appropriately.

**Comment by mishmosh** [comment]
@2color can you pair program this one with @damedoteth and show them how to use github search + browser editor to make these changes?

1. Search for the term "weekly" in this repo.
<img width="761" alt="image" src="https://user-images.githubusercontent.com/1306020/227033653-698b9a02-25b3-4eb2-9a4f-5d2c6ea7ff6d.png">

2. Read the markdown/code and select which files need to be edited.

3. Make the edits in the Github web editor, creating a new branch & PR for all related edits.
