### ISSUE TITLE
Discord Link is invalid

### ISSUE THREAD

**Issue by parthshah1** [ipfs/ipfs-blog#579]
Hi, the discord link in [blog](https://github.com/ipfs/ipfs-blog/blob/main/src/_blog/welcome-to-ipfs-news-172.md) is invalid. When we visit the discord link mentioned in the blog. It displays. 

![Screenshot 2023-05-15 at 12 35 13 PM](https://github.com/ipfs/ipfs-blog/assets/23136779/71f5839e-c46d-4410-a7fd-c05d0bd4be99)

I am not sure though if this is intentional given it is either private or invite only. I might me mistaken.

Cheers.

**Comment by 2color** [comment]
Thanks! Please use https://discord.com/invite/vj7qWuAyHY
