### ISSUE TITLE
SSL cert broken?

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-blog#685]
SSL cert broken?

<img width="1191" alt="Screen Shot 2024-04-16 at 19 53 57" src="https://github.com/ipfs/ipfs-blog/assets/138401/42523811-0e72-462f-a083-08259c383a41">

**Comment by jbenet** [comment]
<img width="1191" alt="Screen Shot 2024-04-16 at 19 54 52" src="https://github.com/ipfs/ipfs-blog/assets/138401/e60c5edb-5f4c-44a2-9167-30311cb5b6ad">

**Comment by jbenet** [comment]
Oh wow, this seems to be across all of ipfs.io

<img width="1191" alt="Screen Shot 2024-04-16 at 19 57 23" src="https://github.com/ipfs/ipfs-blog/assets/138401/7a847f90-bdc8-458a-8c67-3f961992a53a">

**Comment by lidel** [comment]
@jbenet  are you are in a hotel that uses DNS-based filtering?
https://domain.opendns.com/ipfs.io 
Switch DNS to 1.1.1.1 or 8.8.8.8 and the problem will likely go away. 

ps. this is why we moved most websites to `ipfs.tech` (https://github.com/protocol/bifrost-infra/issues/2018)
For blog we link to https://blog.ipfs.tech.

**Comment by jbenet** [comment]
> @jbenet are you are in a hotel or similar place that uses DNS-based filtering?

ooooh lol, ok, great! 

Confirmed with proxies & VPN -- looks like it works fine outside.
false alarm, thank you! 🙇 

> https://blog.ipfs.tech/

ipfs.tech is blocked too, FYI. (that's what threw me off)
