### ISSUE TITLE
Enable comments when loaded via http://localhost:8080/ipns/blog.ipfs.io/

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-blog#80]
Right now comments do not load for users of IPFS Companion due to DNSLink redirect.
I think we should  at least whitelist the default local gateway, it will probably fix it for most users.

Not sure who has the admin on http://discuss.ipfs.io/, but AFAIK we just need to whitelist <del> `http://localhost:8080/ipns/blog.ipfs.io/` </del> `http://blog.ipfs.io.ipns.localhost:8080`   as a valid embed URL.

**Comment by jessicaschilling** [comment]
Re-opening for further troubleshooting as first batch of post-launch work. @zebateira and/or @jdiogopeixoto, can you please have a look? 🙏

**Comment by jessicaschilling** [comment]
@lidel Am afraid that approach didn't work 😟  Do you have time to troubleshoot this with @zebateira and/or @jdiogopeixoto at some point?

**Comment by jessicaschilling** [comment]
Re-opening this issue until we can confirm that #120 fixed this.

**Comment by lidel** [comment]
I  confirm, this is fixed on the local origin (`http://blog.ipfs.io.ipns.localhost:*`)
