### ISSUE TITLE
Add performance instrumentation to ongoing metrics

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-blog#84]
Per @atopal request, we need to add some form of site performance instrumentation to (at minimum) the primary IPFS websites going forward:
- New blog.ipfs.io
- Existing blog.ipfs.io (this may simply be some sort of baseline measurement, considering we are so close to relaunch)
- Existing ipfs.io (for comparison purposes)
- Replatformed ipfs.io
- docs.ipfs.io

Kicking this work off in this repo, since we're already doing a lot of pre-launch work on the blog.

@zebateira: Can you please research potential approaches? Some notes:
- @atopal is partial to [SpeedCurve](https://speedcurve.com/), but it's a commercial service with whom we don't currently have an account, so we should evaluate the larger landscape
- This is likely to scale to all PL websites, so a larger scope may be a cost consideration if we utilize a commercial service
- Data would be repurposed in our reporting dashboards, so bonus points for a programmatic way of getting it into Observable

@atopal: Please edit this comment or add additional comments for any other specs or notes. I'm tentatively labeling this as P2, on the assumption that it's acceptable to work on this post-blog-launch **as long as payload problems in https://github.com/ipfs/ipfs-blog/issues/41 are resolved for launch** — but please revise if you feel this is needed sooner.

cc @terichadbourne @johnnymatthews @yusefnapora @johndmulhausen for context and/or discussion.

**Comment by jessicaschilling** [comment]
@zebateira - I see you've already got an issue to add this to IPFS docs, and I added https://github.com/ipfs/ipfs-website/issues/9 for the replatformed website. Are you OK closing this issue?

**Comment by zebateira** [comment]
@jessicaschilling yes 👍
